module.exports = {
  mainSidebar: {
    Info: ["home", "laws", "security"],
    "Content Type": [
      "cartoons-and-anime",
      "comics-and-manga",
      "books-and-magazines",
      "academics",
      "courses",
      "documentaries",
      "audiobooks",
      "music-and-podcasts",
      "movies-and-tv-shows",
      "sports",
      "games",
      "software",
      "creative-assets",
    ],
    Sources: [
      "torrents",
      "usenet",
      "direct-downloads",
      "discord",
      "irc",
      "telegram",
      "dc-plus-plus",
      "iptv",
    ],
    Miscellaneous: [
      "browser-extensions",
      "userscripts",
      "paywalls",
      "file-sharing",
      "cloud-storage",
      "media-centre-applications",
      "alt-google",
      "tools",
      "misc",
      "dead",
    ],
  },
};
